CREATE DATABASE IF NOT EXISTS QLKS_DB CHARACTER SET 'UTF8' COLLATE 'UTF8_UNICODE_CI';
Use QLKS_DB;


CREATE TABLE IF NOT EXISTS  KHACHHANG
(
	MAKH			VARCHAR(10)	NOT NULL,
	TENKH			VARCHAR(50)	NOT NULL,
	GIOITINH		VARCHAR(03)	NOT NULL,
	DIACHI			VARCHAR(150)		,
	NGAYSINH		DATE				,
	SDT				INT					,
	CMND			VARCHAR(15)			,
	QUOCTICH		VARCHAR(20)			,

	CONSTRAINT pk_KHACHHANG PRIMARY KEY KHACHHANG(MAKH)
);

CREATE TABLE IF NOT EXISTS THIET_BI
(
	MA_THIETBI			VARCHAR(10)	NOT NULL,
	TEN_THIETBI			VARCHAR(20)	NOT NULL,
	NGAY_NHAP			VARCHAR(20)	NOT NULL,	
	NGAY_XUAT			VARCHAR(10)			,
	TINHTRANG			VARCHAR(20)			,
	VI_TRI				VARCHAR(20)			,		

	CONSTRAINT pk_THIETBI PRIMARY KEY THIET_BI(MA_THIETBI)

);



CREATE TABLE IF NOT EXISTS BANG_KIEM_TRA_DINH_KI


(
	MA_KT_DK			VARCHAR(10) NOT NULL	,
	NGAY_KT				DATE					,	
	GIO_BD				TIME					,
	GIO_KT				TIME					,
	TRANGTHAISAUKT		VARCHAR(20)			,
	GHI_CHU				VARCHAR(100)			,
	CONSTRAINT pk_BANG_KIEM_TRA_DINH_KI PRIMARY KEY BANG_KIEM_TRA_DINH_KI(MA_KT_DK)
);

CREATE TABLE IF NOT EXISTS LOAI_PHONG
(
	MA_LOAIPHONG		VARCHAR(10)	NOT NULL,
	MA_KT_DK			VARCHAR(10)	NOT NULL,	    
	TEN_lOAIPHONG		VARCHAR(20)	NOT NULL,
	SOLUONGNGUOIO		INT						,	
	GIATIEN				INT			NOT NULL,		

	CONSTRAINT pk_LOAIPHONG PRIMARY KEY LOAI_PHONG(MA_LOAIPHONG),
	CONSTRAINT fk_BANG_KIEM_TRA_DINH_KI FOREIGN KEY (MA_KT_DK) REFERENCES BANG_KIEM_TRA_DINH_KI(MA_KT_DK)
);



CREATE TABLE IF NOT EXISTS PHONG
(
	MA_PHONG			VARCHAR(10)	NOT NULL,
	MA_LOAIPHONG		VARCHAR(10)	NOT NULL,		
	MA_THIETBI			VARCHAR(20)	NOT NULL,
	TEN_PHONG			VARCHAR(20)	NOT NULL,
	SONGUOIO			INT						,	
	TINHTRANG			VARCHAR(20)	NOT NULL,	
	CONSTRAINT pk_PHONG PRIMARY KEY PHONG(MA_PHONG),
	CONSTRAINT fk_LOAIPHONG FOREIGN KEY (MA_LOAIPHONG) REFERENCES LOAI_PHONG(MA_LOAIPHONG),
	CONSTRAINT fk_THIETBI FOREIGN KEY (MA_THIETBI) REFERENCES THIET_BI(MA_THIETBI)
);

CREATE TABLE IF NOT EXISTS DV
(
	MA_DV				VARCHAR(10)	NOT NULL,
	TENDV				VARCHAR(50)	NOT NULL,
	NGAYDATDV			DATE			NOT NULL,
	SOLUONG				INT						,
	GIO_BD				TIME					,
	GIO_KT				TIME					,
	SONGUOITHAMGIA		INT						,
	GIA					INT						,
	DANHGIACUAKH		VARCHAR(100)			,

	CONSTRAINT pk_DV PRIMARY KEY DV(MA_DV)
);


CREATE TABLE IF NOT EXISTS PHIEU_DV
(
	MAPHIEUDV			VARCHAR(10)	NOT NULL,
	MA_DV				VARCHAR(50)	NOT NULL,
	TENDV				VARCHAR(50)	NOT NULL,
	TONGTIENDV			INT				,

	CONSTRAINT pk_PHIEU_DV PRIMARY KEY PHIEU_DV(MAPHIEUDV),
	CONSTRAINT fk_DICHVU1 FOREIGN KEY (MA_DV) REFERENCES DV(MA_DV)
);

CREATE TABLE IF NOT EXISTS PHIEUTHUEPHONG
(
	MA_PT			VARCHAR(10)	NOT NULL,
	MA_DATPHONG		VARCHAR(10)			,
	MA_PHONG		VARCHAR(10)	NOT NULL,
	MAPHIEUDV		VARCHAR(10)	NOT NULL,
	MAKH			vARCHAR(10)	NOT NULL,
	TENKH			VARCHAR(50)	NOT NULL,
	NGAYDAT			DATE				,		
	NGAYNHAN		DATE				,
	SONGAYO			INT					,		

	CONSTRAINT pk_PHIEUTHUEPHONG PRIMARY KEY PHIEUTHUEPHONG(MA_PT),
	CONSTRAINT fk_PHONG FOREIGN KEY (MA_PHONG) REFERENCES PHONG(MA_PHONG),
	CONSTRAINT fk_PHIEU_DV FOREIGN KEY (MAPHIEUDV) REFERENCES PHIEU_DV(MAPHIEUDV),
	CONSTRAINT fk_KHACHHANG1 FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)
);


CREATE TABLE IF NOT EXISTS HOADON_THANHTOANPHONG
(
	MA_HD_TTP		VARCHAR(10)	NOT NULL,
	MA_PT			VARCHAR(10)	NOT NULL,
	MAKH			VARCHAR(10)	NOT NULL,
	TENKH			VARCHAR(50)	NOT NULL,
	NGAYTHANHTOAN	DATE					,
	TIENPHONG		INT						,
	TONGTIENDV		INT						,
	PHUTHU			INT						,
	TONGTIEN		INT						,	
		CONSTRAINT pk_HOADON_THANHTOANPHONG PRIMARY KEY HOADON_THANHTOANPHONG(MA_HD_TTP),	
		CONSTRAINT fk_PHIEUTHUEPHONG1 FOREIGN KEY (MA_PT) REFERENCES PHIEUTHUEPHONG(MA_PT),
		CONSTRAINT fk_KHACHHANG2 FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)	
);





CREATE TABLE IF NOT EXISTS HOA_DON
(
	MA_HD		VARCHAR(10)	NOT NULL,
	MA_HD_TTP	VARCHAR(10)	NOT NULL,
	TEN_HD		VARCHAR(50)			,
	LOAI_HD		VARCHAR(50)	NOT NULL,		
			
	CONSTRAINT pk_HOA_DON PRIMARY KEY HOA_DON(MA_HD),
	CONSTRAINT fk_HOADON_THANHTOANPHONG FOREIGN KEY (MA_HD_TTP) REFERENCES HOADON_THANHTOANPHONG(MA_HD_TTP)

);

CREATE TABLE IF NOT EXISTS NHANVIEN
(	
	MANV		VARCHAR(10)	NOT NULL,
	TENNV		VARCHAR(50)	NOT NULL,
	GIOITINH	VARCHAR(03)	NOT NULL,
	DIACHI		VARCHAR(150)		,
	NGAYSINH	DATE				,
	SDT			INT					,
	EMAIL		VARCHAR(50)			,
	QUOCTICH	VARCHAR(20)			,

	CONSTRAINT pk_NHANVIEN PRIMARY KEY NHANVIEN(MANV)

);

CREATE TABLE IF NOT EXISTS THONGKE
(
	MA_THONGKE		VARCHAR(10)	NOT NULL,
	MANV			VARCHAR(10)	NOT NULL,
	TEN_THONGKE		VARCHAR(10)	NOT NULL,
	LOAI_THONGKE	VARCHAR(50)	NOT NULL,
	NGAYLAP			DATE					,			

	CONSTRAINT pk_THONGKE PRIMARY KEY THONGKE(MA_THONGKE),
	CONSTRAINT fk_NHANVIEN1 FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);


CREATE TABLE IF NOT EXISTS CHUCVU
(
	MA_CV			VARCHAR(10)	NOT NULL,
	MANV			VARCHAR(10)	NOT NULL,
	TEN_CV			VARCHAR(50)	NOT NULL,	

	CONSTRAINT pk_CHUCVU PRIMARY KEY CHUCVU(MA_CV),
	CONSTRAINT fk_NHANVIEN2 FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);


CREATE TABLE IF NOT EXISTS CHAM_CONG
(
	MA_CC			VARCHAR(10)	NOT NULL,
	MANV			VARCHAR(10)	NOT NULL,
	NGAYCHAM		DATE				,
	GIOCHAM			INT					,
	SOGIOLAM		INT					,			

	CONSTRAINT pk_CHAM_CONG PRIMARY KEY CHAM_CONG(MA_CC),
	CONSTRAINT fk_NHANVIEN3 FOREIGN KEY (MANV) REFERENCES NHANVIEN(MANV)
);





















